version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  eureka-server:
    build: ./eureka-server
    ports:
      - "8762:8762"
    depends_on:
      - mysql-db

  api-gateway:
    build: ./api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server

volumes:
  mysql_data:
